Improve ClassLiteralTransformer
The unsigned client has a Class.forName() method with two differences:

* The NoClassDefFoundError is created with a slightly different sequence
  of instructions.

* The arms of the if/else statement for initializing the synthetic field
  if it is null are swapped.

This commit adds support for translating Class.forName() methods with
either or both of these differences to the modern LDC form.

Signed-off-by: Graham <gpe@openrs2.dev>